// EECS 348 Assignment 1
// Purpose: C program that gives user 3 attempts to guess a secret number between 1 and 10
// Author: Sydney Moroney
// Inputs: takes in user input for guess
// Outputs: outputs too high or low, win or lose
// Collaborators: Madelyn Armitage, Mikayla Pelletier, Savena Lin. Each helped conceptually with changes to be made and helped me troubleshoot issues with program. Madelyn also helped me set up my files for the assignment
// Sources: Fully generated by CoPilot unless stated otherwise
// Sources: Fully generated by CoPilot unless stated otherwise
// Creation Date: 9/8/26
// Last Revision Date: 9/8/26
// Revisions: added comments and checked for edge cases

#include <stdio.h>

int main() {
    int secret = 7;// fixed secret number
    int guess; //intializes guess variable as an int
    int attempts = 3;//user given 3 guesses

    printf("Guess a number between 1 and 10.\n");

    for (int i = 1; i <= attempts; i++) {
        // %d/%d generated by Claude. Original from CoPilot was %d/%3d
        printf("Attempt %d/%d. Enter your guess: ", i, attempts); //Prints attempts out of 3 in __/3 format and asks for input from user

        // Check if scanf successfully reads an integer
        if (scanf("%d", &guess) != 1) { //gets input from user
            printf("Invalid input! Please enter a number.\n"); //Prints this if guess is not an integer

            // Clear the input buffer
            int c;
            while ((c = getchar()) != '\n' && c != EOF);

            i--; // Do not count this attempt
            continue; //jumps to next iteration of for loop
        }

        // Check range
        if (guess < 1 || guess > 10) {
            printf("Out of range! Enter a number between 1 and 10.\n"); //Prints if guess is not between 1 and 10
            i--;    // Do not count this attempt
            continue; //jumps to next iteration of for loop
        }

        if (guess == secret) { //checks if guess is equal to secret number
            printf("Correct! You win!\n"); // prints "Correct! You win!" if the guess is equal to the secret number
            return 0; //stop immediately, end of main if user wins
        } else if (guess < secret) { //if its not equal, checks if guess is lower than secret number
            printf("Too low! Try again.\n"); //prints "Too low! Try again." if guess is lower than the secret number
        } else { //following block runs if guess is not equal or lower to the secret number
            printf("Too high! Try again.\n"); //prints "Too high! Try again." if the guess is higher than the secret number
        }
    }
    printf("Sorry, you lose. The number was %d.\n", secret); //Prints loss message and reveals the secret number.
    return 0; //end of main if user loses
}
